bluetooth.startAccelerometerService()
bluetooth.startButtonService()
bluetooth.startIOPinService()
bluetooth.startLEDService()
basic.showString("MONITOR SERVICES")
bluetooth.startTemperatureService()
